version: "3.0"
services:
    signal_timer:
        build:
            context: ../
            dockerfile: docker/Dockerfile
        environment:
            MODULE_NAME: "signal-timer"
            MODULE_TYPE: "Processing"
            INGRESS_HOST: "0.0.0.0"
            INGRESS_PORT: "80"
            EGRESS_URLS: "https://testdockercompose.free.beeceptor.com"
            LOG_LEVEL: "DEBUG"
        ports:
            - 80:80
